import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
// import { Toaster } from "react-hot-toast";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-white" lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
